### ISSUE TITLE
Import data from ResourceMap's CSV

### ISSUE THREAD

**Issue by nditada** [instedd/facility-public-portal#105]
Use a CSV exported from ResMap, NOT from the API. This is the data schema:
http://resourcemap.instedd.org/en/collections/1890/layers

**Comment by steesdale** [comment]
When ready - let me know and I can provide the specific csv to use; with the prefered fields.

**Comment by bcardiff** [comment]
Send it via email. Highlight if there is localized values of field to use for example amharic version of services names.
