### ISSUE TITLE
[Mobile] Issues in Advanced Search

### ISSUE THREAD

**Issue by pmallol** [instedd/facility-public-portal#107]
version: 66d904c
Tested with iPhone 5s and Chrome browser

1. Navigate to Vitalwave in a Chrome browser
2. Go to Map view
3. Select the Advanced Search icon
4. Tap on the input fields and drop down menus and write or select different options

Obtained:
The page does not show the Search button. The user cannot scroll up and down.
Buttons don't look like the original [design](https://projects.invisionapp.com/d/main#/console/8051401/179312966/preview).
After tapping on a input field and writing any letter or word, the page appears zoomed in (check second image).

![img_2016-11-16 15 12 16](https://cloud.githubusercontent.com/assets/9214460/20360013/f345fd7e-ac10-11e6-81a8-f15fbb083b6e.jpg)

![img_2016-11-16 15 12 21](https://cloud.githubusercontent.com/assets/9214460/20359883/7a417c96-ac10-11e6-925a-3c3c3f993841.jpg)

**Comment by juanedi** [comment]
Usability issues should now be fixed. I opened a separate ticket #116 for improving the styles of combo boxes.

**Comment by pmallol** [comment]
Ok in version: 945bc20
