### ISSUE TITLE
Facility services get hidden when window is resized

### ISSUE THREAD

**Issue by pmallol** [instedd/facility-public-portal#123]
version: 945bc20

1. In map view search for facility 'Addis Raey Health Center'
2. Observe the last services it provides
3. Resize the browser window

Obtained: 
Last facility services are hidden
![screen shot 2016-11-23 at 3 57 04 pm](https://cloud.githubusercontent.com/assets/9214460/20574910/a4bdbc70-b195-11e6-9136-558a1e644aa5.png)
![screen shot 2016-11-23 at 3 57 29 pm](https://cloud.githubusercontent.com/assets/9214460/20574911/a4bff8be-b195-11e6-9b1d-6d284897ad1a.png)

**Comment by bcardiff** [comment]
This will be fixed together with the changes for #130

**Comment by pmallol** [comment]
Ok in version: 3bbeb63
