### ISSUE TITLE
Advanced search autocomplete options are hidden when overflowing map control

### ISSUE THREAD

**Issue by juanedi** [instedd/facility-public-portal#128]
<img width="480" alt="screen shot 2016-11-30 at 12 55 23 pm" src="https://cloud.githubusercontent.com/assets/753421/20759679/602476a0-b6fc-11e6-8792-2ce4d0555899.png">

**Comment by bcardiff** [comment]
There is no clear winner here. Container is fixed and controls are at the very bottom. Maybe they should render up instead of down when there is no much space, but even so, if the window is small enough the control won't come out of the window as native dropdowns. Any suggestion @jkicillof?

**Comment by jkicillof** [comment]
The control should come out of the window, that's the winner.

**Comment by bcardiff** [comment]
fixed at c5f56a5add178c218320ddbb59486847d33170c1 services menu will pull up and the location will pull down. As a compromise solution should be good enough.

**Comment by pmallol** [comment]
Ok in version: 3bbeb63
