### ISSUE TITLE
"Not found" and "loading" view

### ISSUE THREAD

**Issue by juanedi** [instedd/facility-public-portal#13]
When no matches/suggestions are found, display something nicer than this:
<img width="465" alt="screen shot 2016-09-26 at 5 08 41 pm" src="https://cloud.githubusercontent.com/assets/753421/18849989/e96302de-840b-11e6-93e3-982f42444ec9.png">

Same happens when results are being loaded:
![screen shot 2016-10-05 at 2 18 04 pm](https://cloud.githubusercontent.com/assets/9214460/19123804/92042890-8b06-11e6-8f2e-c404f08e500e.png)

**Comment by pmallol** [comment]
Ok in version d52b84d
