### ISSUE TITLE
Wrong layout of locations in autocomplete

### ISSUE THREAD

**Issue by bcardiff** [instedd/facility-public-portal#131]
![screen shot 2016-12-06 at 2 31 30 pm](https://cloud.githubusercontent.com/assets/459923/20936281/d0e5d87a-bbc0-11e6-8c9a-4c062310f921.png)

Seems to be triggered because the sidebar has no fixed width when it is expanded.

present at 9fb67e2fba6ed4ad531ad9fe3a03a1e5a012838c

**Comment by juanedi** [comment]
Will be fixed along #130.

**Comment by pmallol** [comment]
Still not fixed in version 3bbeb63
