### ISSUE TITLE
'Something went wrong' error when changing to Amharic

### ISSUE THREAD

**Issue by pmallol** [instedd/facility-public-portal#133]
version: 3bbeb63

1. Go to Vitalwave landing page
2. Click on 'አማርኛ' to change language to Amharic
3. Click the search blue button 'ፍለጋ'

Obtained:
The user is redirected to the Map view and an error notice appears on the top right corner reading "Something went wrong. You may want to refresh the application." A facility can be searched but not accessed when clicked.

**Comment by steesdale** [comment]
This seems to be working now.

**Comment by pmallol** [comment]
That's right, thank you @steesdale! 
Ok in version: 2ece9b
