### ISSUE TITLE
Simplify/expose how to upload pictures for facilities

### ISSUE THREAD

**Issue by nditada** [instedd/facility-public-portal#145]
Pictures here: https://drive.google.com/drive/folders/0ByATyJhcn2gdRGlyOHRfN0dnLTA

**Comment by pmallol** [comment]
@nditada all the folders inside the link seem to be empty.

**Comment by bcardiff** [comment]
The process is described in the importing doc https://github.com/instedd/facility-public-portal/blob/377685fbc3fb02dd730a52508edc1e89b50051f3/docs/importing.md#normalizing-resourcemap-information 

preview of result at
http://g.recordit.co/EbLcxdIqeH.gif
