### ISSUE TITLE
Add "Ethiopian_national_identifier"

### ISSUE THREAD

**Issue by nditada** [instedd/facility-public-portal#147]
Maybe small at the bottom? Or as a tooltip somewhere? It needs to be accesible but most people will not need it. cc @jkicillof

**Comment by jkicillof** [comment]
I think it should be below the facility name, next to the category, where all the identification data is.
https://projects.invisionapp.com/d/main#/console/8051401/172380322/preview
https://projects.invisionapp.com/d/main#/console/8037548/172084047/preview

**Comment by pmallol** [comment]
Should this information be available in the api as well? 
https://vitalwave-stg.instedd.org/docs

**Comment by steesdale** [comment]
Yes

**Comment by pmallol** [comment]
Thank you Scott!

**Comment by pmallol** [comment]
@bcardiff  Still missing:
- [ ] exporting this information through the API
- [ ] Update DOCS:  https://vitalwave-stg.instedd.org/docs

**Comment by bcardiff** [comment]
It was added at the bottom of the details.

http://g.recordit.co/EbLcxdIqeH.gif
