### ISSUE TITLE
Branding Issues in Portals

### ISSUE THREAD

**Issue by steesdale** [instedd/facility-public-portal#167]
For https://aslm-labmap.instedd.org/ & https://niger-labmap.instedd.org/map 

There are two spots with some branding issues... 

1) The icon in the browser tab; shows the Ethiopia symbol; when it should show the ASLM or Niger symbol respectively. 

2) The map image on the "About" page; has Ethiopia branding and ideally would be generic or specific to the project.

<img width="1511" alt="screen shot 2019-02-07 at 8 57 42 pm" src="https://user-images.githubusercontent.com/3987608/52456718-b60e1b80-2b1b-11e9-85e1-d8e36b88c68b.png">

**Comment by nditada** [comment]
(1) might be something we can fix. (2) should be definitely generic, customizing those mockups for each deployment would be overkill

**Comment by bcardiff** [comment]
Maybe the image there can be turned into an SVG with a generic map. So the logo and colors could be rebranded with the same mechanism of the rest of the site. Or the image can be rethought/replaced with something agnostic to the branding.

**Comment by steesdale** [comment]
+1 for something generic...

**Comment by jkicillof** [comment]
![devices](https://user-images.githubusercontent.com/5031636/52715846-3bf6f000-2f7c-11e9-968e-6336c8c7df31.png)
@steesdale does the ASLM branding count as generic?
Regarding the favicon, it should be taken from www.aslm.org

**Comment by steesdale** [comment]
No it is not generic...





--
Scott Teesdale
Program Development Lead - InSTEDD
Email: steesdale@instedd.org
Skype: scott.teesdale
Social: Twitter / LinkedIn

**Comment by jkicillof** [comment]
![devices](https://user-images.githubusercontent.com/5031636/52724547-51751580-2f8e-11e9-8d3d-af8ccf5277da.png)
like this?

**Comment by steesdale** [comment]
Looks good.  Lets proceed with getting these updated

**Comment by waj** [comment]
Fixed in 0.4.2
