### ISSUE TITLE
Rename headers in Ona importing process

### ISSUE THREAD

**Issue by lmatayoshi** [instedd/facility-public-portal#182]
Rename headers according to the following list:
- "_id": "id"
- "section1/section1.1/facility_name": "Facility name"
- "section1/section1.1/_general_gps_coordinates_latitude": "Latitude"
- "section1/section1.1/_general_gps_coordinates_longitude": "Longitude"
- "section1/section1.1/city": "City/District"
- "section1/section1.1/Laboratory_affiliation": "Affiliation"
- "section1/section1.1/laboratory_adress": "Address"
- "section1/section1.1/contact_name": "Contact name"
- "section1/section1.1/contact_email": "Contact email address"
- "section1/section1.1/contact_phone": "Contact phone"
- "end_time": "End time"
- "section1/section1.1/open_hoursm": "Opening time Monday"
- "section1/section1.1/close_hoursm": "Closing time Monday"
- "section1/section1.1/open_hoursf": "Opening time Friday"
- "section1/section1.1/close_hoursf": "Closing time Friday"
- "section1/section1.1/open_hourssa": "Opening time Saturday"
- "section1/section1.1/close_hourssa": "Closing time Saturday"
- "section1/section1.1/open_hourssu": "Opening time Sunday"
- "section1/section1.1/close_hourssu": "Closing time Sunday"
- "section1/section1.1/days": "days"

**Comment by lmatayoshi** [comment]
This commit affects `data.csv` file, which is used in Ona importing process.

@mmuller , to verify this:
1. Import a `data.csv` file replacing old headers that includes "section" prefixes with the new ones
2. Import should be successful
3. When clicking: "Download full dataset", you should obtain the following values:
    1. `id` column in full dataset should match `id` column in `data.csv`
    2. `name` column in full dataset should match `Facility name` column in `data.csv`
    3. `lat` column in full dataset should match `Latitude` column in `data.csv`
    4. `lng` column in full dataset should match `Longitude` column in `data.csv`
    5. `facility_type` column in full dataset should equal "laboratory" for all rows
    6. `ownership` column in full dataset should match `Affiliation` column in `data.csv`
    7. `address` column in full dataset should match `Address` column in `data.csv`
    8. `contact_name` column in full dataset should match `Contact name` column in `data.csv`
    9. `contact_email` column in full dataset should match `Contact email` column in `data.csv`
    10. `contact_phone` column in full dataset should match `Contact phone` column in `data.csv`
    11. `opening_hours` should be properly computed according to Opening and Closing times for:
        - Monday
        - Friday
        - Saturday
        - Sunday

**Comment by manumoreira** [comment]
The objective of this task is to avoid specific header names that only apply to one ONA form and replacing them by generic header names to which any form can be adapted to.
