### ISSUE TITLE
Close button behaviour in facility detail

### ISSUE THREAD

**Issue by juanedi** [instedd/facility-public-portal#22]
Pressing the "close" button while viewing a facility's detail currently navigates back in the browser's history. This causes the following two unexpected behaviours:

Case 1:
- Open any other website in the browser
- Enter a link to a facility's detail
- Press the close button
- Note that the browser leaves our application and navigates to the other website.

Case 2:
- Perform a search that yields multiple results
- Repeteadly select different facilities
- Press the close button
- Note that the history of visited facilities is replayed backwards. I would probably expect to go directly to the search result list.

**Comment by pmallol** [comment]
Ok in d52b84d
