### ISSUE TITLE
Search suggestions are not scrollable

### ISSUE THREAD

**Issue by pmallol** [instedd/facility-public-portal#23]
In version 4819e2c

![facility public portal](https://cloud.githubusercontent.com/assets/9214460/19090666/d19bb8f8-8a55-11e6-9e06-b540064b740f.png)

**Comment by juanedi** [comment]
Fixed in 145929f0a5ed8d8ff916e27bd31694a186c2364e

**Comment by pmallol** [comment]
Ok in b1167d6
