### ISSUE TITLE
Padding for markers when fitting map bounds

### ISSUE THREAD

**Issue by juanedi** [instedd/facility-public-portal#27]
Steps:
- Navigate to a facility's url
- Click the button to geolocate the user

Observe that after geolocation the map adjusts it's bounds to fit both markers at it's borders (see screenshot below). We should probably use leaflet's padding option when fitting bounds.

<img width="1630" alt="screen shot 2016-10-06 at 2 42 17 pm" src="https://cloud.githubusercontent.com/assets/753421/19163707/730e1e64-8bd3-11e6-8dd1-e481f0f23634.png">

**Comment by vtiffenberg** [comment]
Can not reproduce at this time. We think it's been resolved while doing a different task

**Comment by pmallol** [comment]
Couldn't reproduce it either, ok in version 528019b
