### ISSUE TITLE
Add Mobile Shortcut metadata

### ISSUE THREAD

**Issue by edjez** [instedd/facility-public-portal#29]
So it looks more like an app when the bookmark is saved in a phone. Great for bizdev.
I mean stuff like this
```

<link rel="apple-touch-icon-precomposed" sizes="57x57" href="img/blabla/icon57.png" />
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/blabla/icon72.png" />
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/blabla/icon114.png" />
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/blabla/icon144.png" />

<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Ethiopia Health Facilities">
```

**Comment by bcardiff** [comment]
@jkicillof can we have some icons with the following sizes for using in mobile devices?

60×60	iPhone & iPod Touch (Non-Retina)
76×76	iPad 2 & iPad mini (Non-Retina)
120×120	iPhone & iPod Touch (Retina)
152×152	iPad & iPad mini (Retina)

source: http://blog.teamtreehouse.com/optimizing-mobile-web-apps-ios

**Comment by pmallol** [comment]
Tested on Iphone 5s
![img_2016-10-18 11 56 22](https://cloud.githubusercontent.com/assets/9214460/19483203/e9d61f1a-9529-11e6-8fcf-43141b4abda9.jpg)
