### ISSUE TITLE
Display facilities based on their type and current zoom level

### ISSUE THREAD

**Issue by juanedi** [instedd/facility-public-portal#30]
To avoid displaying a huge amount of big markers on low zoom levels, determine how to display a facility based on the following rules:

- Determine a hierarchy based on the facility type field
- Facilities of the highest hierarchy level should always be displayed
- Lower hierarchy levels should be displayed with small markers only up to a point
- Above a certain (to be determined) threshold, markers for lower hierarchy facilities should not be displayed to avoid cluttering the map.

**Comment by juanedi** [comment]
We decided that, at least until we get some feedback, we will filter results by facility type based on the current zoom level (ie. don't show small markers for low-level facilities when the result count is below a certain threshold).

**Comment by mmuller** [comment]
Ok in version daea450
