### ISSUE TITLE
Map needs a scale

### ISSUE THREAD

**Issue by edjez** [instedd/facility-public-portal#48]
Expected: Map shows a linear scale.
Current: it never shows a scale.
GIS basics.. "A map without a scale is [a diagram]"  (at best... replace with "frustrating","sketch", "trash", "entertainment", depending on the attitude of the user).
A lot of reviewers will also be looking at large -scale features where implicit human scale indicators are missing (eg not looking at urban blocks & streets but a rural area)

Additionally, it may be useful to display "Approx xx km away" in the facility details page.

**Comment by bcardiff** [comment]
the scale is display in the map toolbar in the bottom right corner.

![scale](https://cloud.githubusercontent.com/assets/459923/19532657/19e5f48e-9613-11e6-8337-421e040a264c.png)

**Comment by mmuller** [comment]
Ok in version daea450
