### ISSUE TITLE
Mobile: 'Report an issue' popup does not adjust to screen

### ISSUE THREAD

**Issue by pmallol** [instedd/facility-public-portal#49]
Version d52b84d
Tested on iPhone 5s

![img_2016-10-18 16 55 28](https://cloud.githubusercontent.com/assets/9214460/19494052/b61481ce-9553-11e6-94a8-4912bc317077.jpg)

**Comment by vtiffenberg** [comment]
Fixed by https://github.com/instedd/facility-public-portal/commit/d6ad1ec3acecefd0b0d51cb7bb2757d34031ecf5

**Comment by pmallol** [comment]
Ok in version: 66d904c
