### ISSUE TITLE
Maximum zoom level doesn't fit the whole country in the screen

### ISSUE THREAD

**Issue by pmallol** [instedd/facility-public-portal#52]
Found in version 8a205fe

Some facilities still get hidden even though the zoom is at its maximum level.

![screen shot 2016-10-19 at 11 59 30 am](https://cloud.githubusercontent.com/assets/9214460/19524780/41ecff86-95f5-11e6-823a-0d005104f563.png)

**Comment by bcardiff** [comment]
It depends on both zoom and window size the limit. I don't think we will ensure that the whole country is visible despite the screen size. Yet, maybe, the current zoom limit could be lifted.

**Comment by vtiffenberg** [comment]
Decided not to make any changes to current zoom adjustments per Brian's previous comment. Will close.
