### ISSUE TITLE
Production: Non ascii chars issues in env variables (locale names can be ascii only)

### ISSUE THREAD

**Issue by bcardiff** [instedd/facility-public-portal#62]
Right now the production environment uses env variable to load available locales.
Non ascii chars are loaded with wrong encoding in the docker image. So the following fails to start the app:

```
    - SETTINGS__LOCALES__AM=አማርኛ
    - SETTINGS__LOCALES__EN=English
    - SETTINGS__LOCALES__ES=Español
```

Currently english ascii safe version of locales are used, but this should change.

```
    - SETTINGS__LOCALES__AM=Amharic
    - SETTINGS__LOCALES__EN=English
    - SETTINGS__LOCALES__ES=Spanish
```

Maybe is a setting of the docker image and not an issue of docker cloud.

Neither forcing encoding of strings, nor escaping in the stackfile with utf sequence seems to work.

**Comment by bcardiff** [comment]
Maybe we can override a production.yml from /data with the corresponding locale names and forget about env variables for locales.

**Comment by juanedi** [comment]
Locale settings are now being defined in a production.yml file mounted as a data volume in the app container.
