### ISSUE TITLE
Add zoom in/out buttons for desktop version

### ISSUE THREAD

**Issue by mmuller** [instedd/facility-public-portal#63]
<img width="317" alt="screen shot 2016-10-26 at 3 33 06 pm" src="https://cloud.githubusercontent.com/assets/518152/19739509/97eba5a8-9b91-11e6-9898-9bab7fdabb6f.png">

**Comment by steesdale** [comment]
This is a priority

**Comment by mmuller** [comment]
Ok in version 4b54f4b
