### ISSUE TITLE
Data export

### ISSUE THREAD

**Issue by juanedi** [instedd/facility-public-portal#72]
The scope document mentions has an "export full list of data" item. Does this mean we should dump the whole dataset in a specific format? Or just serve the raw dataset we used to build the application?

**Comment by vtiffenberg** [comment]
Implemented a full dataset export (same as input). Not search specific.

**Comment by vtiffenberg** [comment]
Move the download button to menu. Do not implement search-specific download

**Comment by mmuller** [comment]
Ok in version 4b54f4b
