### ISSUE TITLE
Improve access to advanced search

### ISSUE THREAD

**Issue by juanedi** [instedd/facility-public-portal#75]
Currently the advanced search feature is available by pressing a button that appears below the suggestions. This means that the user needs to start typing in order to see that button.

It is especially inconvenient in the following scenario:
- The user performs an advanced search
- The app displays the search results
- The user wants to modify one of the filters of the advanced search he/she just performed, but needs to start typing something in order to see the advanced search button.

**Comment by steesdale** [comment]
A user may want to start with advanced search -- before searching.  Can there be something like a button in the search bar or an option to more easily access this.    +1

**Comment by pmallol** [comment]
Ok in version: 66d904c
