### ISSUE TITLE
Results pagination and bounding box

### ISSUE THREAD

**Issue by juanedi** [instedd/facility-public-portal#8]
Elastic search limits the number of results returned per request. The number can be controlled using the from/size parameters.

We should probably use the map's visible area to define a bounding box, and then retrieve all result pages that match that bounded query.

**Comment by bcardiff** [comment]
As of b5e57cd5671c59be5d9985f9345528b3079f7af8 this is fixed.

* Load more is performed to add facilities marker as long as markers fits inside de screen.
* When the user moves more results are fetched.

**Comment by mmuller** [comment]
Ok in version daea450
