### ISSUE TITLE
Hitting enter in advanced search triggers a page reload

### ISSUE THREAD

**Issue by juanedi** [instedd/facility-public-portal#82]
It seems to perform a native form submission. We are probably attaching the wrong event handler to trigger the search.

**Comment by steesdale** [comment]
This feature is not presenting in the current staging version.

**Comment by juanedi** [comment]
This is not happening currently, it must have changed in recent versions. Still, it would be nice to have the form submitted when the user presses enter.

**Comment by pmallol** [comment]
Ok in version: 66d904c
