### ISSUE TITLE
Download Flat Facility List

### ISSUE THREAD

**Issue by steesdale** [instedd/facility-public-portal#86]
Such as in RM: 

- A user downloads a list of facilities  -  is able to have a flattened single .csv with all sites

**Comment by bcardiff** [comment]
@steesdale Currently the whole dataset is downloaded as a .zip with the facilities but also services and hierarchical location:

```
$ tree ~/Downloads/full_dataset
~/Downloads/full_dataset
├── facilities.csv
├── facilities_services.csv
├── facility_types.csv
├── locations.csv
└── services.csv
```

Is that enough to close this issue or we need *just* the facilities.csv for some reason?

**Comment by juanedi** [comment]
This feature is now tracked with #104.
