### ISSUE TITLE
Landing Page Editor

### ISSUE THREAD

**Issue by nditada** [instedd/facility-public-portal#89]
- URL protected with basic auth.
- 3 content areas (2 half width, 1 full width)
- markdown editor for each

**Comment by juanedi** [comment]
We should allow defining each piece of text in multiple locales, right? @nditada @vtiffenberg

**Comment by vtiffenberg** [comment]
Yes, I forgot about that, we should have 1 version per language

**Comment by nditada** [comment]
@juanedi good point. Yes, I'm pretty sure we should. @steesdale please comment soon if we don't need too.

**Comment by steesdale** [comment]
Yes please proceed

**Comment by pmallol** [comment]
Ok in version: 66d904c
