### ISSUE TITLE
Language links on bottom break single-page navigation

### ISSUE THREAD

**Issue by edjez** [instedd/facility-public-portal#93]
Expected: Clicking on language stays in the page and changes the language
Actual: Opens up a new page / browser with the clicked language and leaves current tab with the existing language.

Excacerbated in iOS if seeing the portal as a mobile web home shortcut.

(sorry if this is a dupe couldn't find what I thought I had posted before)

**Comment by nditada** [comment]
@edjez can you provide a few more details? I can't repro this on Desktop Chrome nor iOS Safari.

**Comment by juanedi** [comment]
@nditada To make it evident, open the app in iOS Safari, press the share button and "add to home screen".

Then, when using the app from the home screen, every link that triggers navigation (ie. URL change not handled by the client) will leave the native-like app and open a separate safari instance.

This happens also when opening the API docs.

**Comment by bcardiff** [comment]
we could add something like when the link is relative http://stackoverflow.com/questions/2898740/iphone-safari-web-app-opens-links-in-new-window

**Comment by steesdale** [comment]
Hi I was able to recreate this one.  Here is what I did.

- I had bookmarked the link in my iphones home page.
- I opened it
- I selected another language
- It then proceeded to open a new window and reload.
