### ISSUE TITLE
Question: How to Customize Email Address 

### ISSUE THREAD

**Issue by steesdale** [instedd/facility-public-portal#97]
For the ET portal - I have an email address I would like to use for reporting errors or for contact to learn more. 

How is this configured?  Email me and I can send the email address

**Comment by bcardiff** [comment]
It is a configuration upon deployment.
It is specified in [config/settings.yml](https://github.com/instedd/facility-public-portal/blob/master/config/settings.yml#L1) or via `SETTINGS__REPORT_EMAIL_TO` environment variable.
For staging environment there is a fake [smtp serverver](https://github.com/djfarrelly/MailDev) to see the emails that have been sent.

**Comment by bcardiff** [comment]
The email in stg environment was updated as requested
